name: audio_recorder_example
description: Demonstrates how to use the audio_recorder plugin.

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.10
  file: ^5.1.0


dev_dependencies:
  audio_recorder:
    path: ../
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true